runners:
  - name: "azure-windows-runner"
    cloud: "azure"
    region: "westus2"
    instance_type: "Standard_E8as_v7"
    machine_image: microsoftvisualstudio:visualstudiowsplustools:vs-latest-comm-ws2025-datacenter-azure-gen2:latest
    labels:
      - "cirun-azure-windows-runner"

  - name: cirun-gcp-2xl
    cloud: gcp
    instance_type: c4a-standard-16
    machine_image: ubuntu-2204-jammy-arm64-v20260520
    region: europe-west4-a
    preemptible: true
    extra_config:
      baseDisk:
        diskSizeGb: 100
    labels:
      - cirun-gcp-2xl
